simplier file format means less code

diff --git a/bin/timeclock b/bin/timeclock
--- a/bin/timeclock
+++ b/bin/timeclock
@@ -6,13 +6,11 @@ if [ ! -f $LOG ]; then
 	touch $LOG
 fi
 
-
-TIMESTAMP=$(date +%s)
 BIWEEKLY_OFFSET=0
 BIWEEKLY_KNOWN="2019-01-21"
 BIWEEKLY_START=$(date -jf "%Y-%m-%d %H%M%S" "$BIWEEKLY_KNOWN 000000" +%s)
 
-while [ $TIMESTAMP -gt $BIWEEKLY_START ]; do
+while [ $(date +%s) -gt $BIWEEKLY_START ]; do
 	BIWEEKLY_OFFSET=$(echo "${BIWEEKLY_OFFSET} + 14" | bc)
 	BIWEEKLY_START=$(date -v+${BIWEEKLY_OFFSET}d -jf "%Y-%m-%d %H%M%S" "${BIWEEKLY_KNOWN} 000000" +%s)
 done
@@ -20,9 +18,9 @@ done
 PERIOD_START=$(date -v-14d -jf "%s" $BIWEEKLY_START "+%s")
 PERIOD_END=$(date -v-1d -jf "%s" $BIWEEKLY_START "+%s")
 
-
 LINES=$(wc -l $LOG | awk '{print $1}')
 LINES=$(echo "$LINES - 1" | bc) # remove ending newline from count
+
 
 human_hours() {
 	h=$(echo "${1}/3600" | bc)
@@ -31,13 +29,13 @@ human_hours() {
 }
 
 log() {
-	SET=$(echo "$LINES + 2" | bc)
+	SET=$LINES
 	PREVDATE="0000"
 
 	while [ $SET -gt 0 ]; do
-		TIMES=$(cat $LOG | tail -${SET} | head -2)
-		START=$(echo "$TIMES" | tail -2 | head -1)
-		END=$(echo "$TIMES" | tail -1)
+		LINE=$(awk "NR==$SET" $LOG)
+		START=$(echo $LINE | awk '{print $1}')
+		END=$(echo $LINE | awk '{print $2}')
 
 		CURRDATE=$(date -jf '%s' $START '+%m%d')
 		if [ "$PREVDATE" -eq "$CURRDATE" ]; then
@@ -48,39 +46,34 @@ log() {
 		fi
 		PREVDATE=$CURRDATE
 
-		if [ $START -ne $END ]; then 
+		if [ -z $END ]; then 
+			echo " ~ " 
+		else
 			echo -n " - "
 			date -jf '%s' $END '+%I:%M %p'
-		else
-			echo " ~ " 
 		fi
 		
-		SET=$(echo "$SET - 2" | bc)
+		SET=$(echo "$SET - 1" | bc)
 	done
 }
 
 payperiod_total() {
 	WORKED=0
+	SET=$LINES
 
-	if [ "$((LINES % 2))" -ne 0 ]; then
-		SET=$(echo "$LINES + 1" | bc)
-		HOURS=$(cat "$LOG" | head -${SET})
-	else 
-		SET=$(echo "$LINES + 2" | bc)
-		HOURS=$(cat $LOG)
-	fi
-	
 	while [ $SET -gt 0 ]; do
-		TIMES=$(echo "$HOURS" | tail -${SET} | head -2)
+		LINE=$(awk "NR==$SET" $LOG)
+		START=$(echo $LINE | awk '{print $1}')
+		END=$(echo $LINE | awk '{print $2}')
 
-		START=$(echo "$TIMES" | tail -2 | head -1)
-		END=$(echo "$TIMES" | tail -1)
+		if [ ! -z $END ] && \
+		   [ $START -gt $PERIOD_START ] && \
+		   [ $START -lt $PERIOD_END ]; then
 
-		if [ $START -gt $PERIOD_START ] && [ $START -lt $PERIOD_END ]; then
 			WORKED=$(echo "($END - $START) + $WORKED" | bc)
 		fi
 
-		SET=$(echo "$SET - 2" | bc)
+		SET=$(echo "$SET - 1" | bc)
 	done
 
 	echo -n "PAYPERIOD:    "
@@ -88,71 +81,67 @@ payperiod_total() {
 }
 
 
+OUT="$(date -jf '%s' $PERIOD_START '+%-m/%d') -"
+OUT="$OUT $(date -jf '%s' $PERIOD_END '+%-m/%d')"
+OUT="$OUT | $(echo "($PERIOD_END - $(date +%s)) / 86400" | bc) days left"
 
-echo -n "$(date -jf '%s' $PERIOD_START '+%-m/%d') - $(date -jf '%s' $PERIOD_END '+%-m/%d')"
-echo " | $(echo "($PERIOD_END - $TIMESTAMP) / 86400" | bc) days left"
-echo "------------------------------"
-echo 
-	
-if [ -n "$1" ]; then
-	case $1 in
-		start)
-			if [ "$(( LINES % 2))" -ne 0 ]; then
-				echo "ERROR: already clocked in"
-				exit 1
-			fi
+echo $OUT
+printf -- '-%.0s' $(seq $(echo -n $OUT | wc -c)) # draws a line
+echo -e "\n"
 
-			date +%s >> "$LOG"
-		
-			echo "STATUS:       clocked in"
 
-			payperiod_total
-			;;
-
-		stop)
-			if [ "$(( LINES % 2))" -eq 0 ]; then
-				echo "ERROR: already clocked out"
-				exit 1
-			fi
-
-			date +%s >> "$LOG"
-
-			echo "STATUS:       clocked out!"
-
-			START=$(cat $LOG | tail -2 | head -1)
-			END=$(cat $LOG | tail -1)
-
-			echo -n "HOURS WORKED: "
-			human_hours $(echo "$END - $START" | bc)
-		
-			payperiod_total
-			;;
-
-		log)
-			log
-			;;
-
-		*)
-			echo "unknown command"
+case $1 in
+	start)
+		if [ "$(tail -1 $LOG | wc -w)" -eq 1 ]; then
+			echo "ERROR: already clocked in"
 			exit 1
-			;;
-	esac
-else
-	if [ "$(( LINES % 2))" -ne 0 ]; then
-		echo "STATUS:       on the clock "
-		
-		START=$(cat $LOG | tail -1)
+		fi
+
+		echo -n $(date +%s) >> "$LOG"
+
+		echo "STATUS:       started working"
+
+		payperiod_total
+		;;
+
+	stop)
+		if [ "$(tail -1 $LOG | wc -w)" -eq 2 ]; then
+			echo "ERROR:        already clocked out"
+			exit 1
+		fi
+
+		echo "STATUS:       stopped working"
+
+		START=$(tail -1 $LOG | awk '{print $1}')
 		END=$(date +%s)
 
-		echo -n "STARTED:      $(date -jf '%s' $START '+%-I:%M %p') ("
+		echo " $END" >> $LOG
 
-		echo -n $(human_hours $(echo "$END - $START" | bc))
-		echo " hours)"
-	else
-		echo "clocked out"
-		echo "-----------"
-		echo
-	fi
+		echo -n "HOURS WORKED: "
+		human_hours $(echo "$END - $START" | bc)
+		
+		payperiod_total
+		;;
 
-	payperiod_total
-fi
+	log)
+		log
+		;;
+
+	*)
+		if [ "$(tail -1 $LOG | wc -w)" -eq 1 ]; then
+			echo "STATUS:       on the clock "
+		
+			START=$(tail -1 $LOG | awk '{print $1}')
+			END=$(date +%s)
+
+			echo -n "STARTED:      $(date -jf '%s' $START '+%-I:%M %p') ("
+
+			echo -n $(human_hours $(echo "$END - $START" | bc))
+			echo " hours)"
+		else
+			echo "STATUS:       clocked out"
+		fi
+
+		payperiod_total
+		;;
+esac
